### ISSUE TITLE
Example that seems to violate the equal-conflict property

### ISSUE THREAD

**Issue by NotANumberYang** [CvO-Theory/apt#9]
Hi,

Thanks again for answering our questions about APT!
While experimenting with APT, we have seen an example for which it seems that APT synthesizes a PN that violates the equal-conflict property. We would like to understand this observation better. 

Below is our input:
![paper_example_input dot](https://github.com/CvO-Theory/apt/assets/26345754/7292ff7b-bd34-4e44-8292-f9a3f1d29eed)

In text:
```
.name "Paper example"
.type LTS

.states
s0[initial]
s2
s3
s1
s4


.labels
t1
t2
t3
t4


.arcs
s0 t3 s2
s0 t2 s3
s0 t1 s1
s3 t1 s4
s1 t2 s4
s2 t4 s0
s4 t4 s0
```

We have used these options: `upto-language-equivalence,plain,pure,safe,equal-conflict,minimize`

And we obtained the synthesis result below:
![paper_example_output dot](https://github.com/CvO-Theory/apt/assets/26345754/022f1de5-7a6e-4008-b74b-2297a193fe00)
In this Petri net, `t1 `and `t3 `have overlapping presets, but the preset of `t1 `is different from the one of `t3`, i.e., `Preset(t1) = {p3}, preset(t3) = {p0,p3}`, so they overlap but are not the same. It seems to violate the equal-conflict property. 

Would you please help us understand this observation better? Do we miss something? Could this be an implementation bug?

**Comment by psychon** [comment]
First: I get the same result. I was too lazy to copy&paste the LTS into a file, so I generated it from a regular expression (this produces a structurally different LTS, but it generates the same prefix language): `java -jar apt.jar reg '(<t3><t4>|<t1><t2><t4>|<t2><t1><t4>)*' | java -jar apt.jar synth upto-language-equivalence,plain,pure,safe,equal-conflict,minimize - -  | java -jar apt.jar pn_convert apt dot - | dot -T png -o bar.png`.

Then: I think you found a bug.

There are several implementations in the code and they are tried one after the other based on your input (in this case `plain,pure,safe,equal-conflict`, the other properties are handled elsewhere). When an implementation does not support the requested properties, it is supposed to throw an exception.
https://github.com/CvO-Theory/apt/blob/f705554f6ba2bc96aed911bbddd74a17a86226ac/src/module/uniol/apt/analysis/synthesize/separation/SeparationUtility.java#L180-L213

Apparently, `ElementarySeparation` just ignores `equal-conflict`.

For testing, I used `-Dapt.debug=true` to look at what is going on. With the original call, this says
```
SeparationUtility: Created Separation instance from class uniol.apt.analysis.synthesize.separation.ElementarySeparation
```
Next, I forced the "catch all fallback implementation" with `-Dapt.separationImplementation=InequalitySystemSeparation`. This says that everything is unsolvable:
```
$ java -jar apt.jar reg '(<t3><t4>|<t1><t2><t4>|<t2><t1><t4>)*' | java -Dapt.separationImplementation=InequalitySystemSeparation -jar apt.jar synth upto-language-equivalence,plain,pure,safe,equal-conflict,minimize - 
success: No
failedStateSeparationProblems: []
failedEventStateSeparationProblems: {t1=[s1, s3], t2=[s2, s3], t3=[s1, s2, s3]}
```
I don't have much time to look into the details right now. I hope the `-Dapt.separationImplementation=InequalitySystemSeparation` I mention above is enough for you for now.

**Comment by psychon** [comment]
I fixed the bug and the output is now the same with and without `-Dapt.separationImplementation=InequalitySystemSeparation` (actually, the fix causes `InequalitySystemSeparation` to always be used):
```
$ java -jar apt.jar reg '(<t3><t4>|<t1><t2><t4>|<t2><t1><t4>)*' | java -jar apt.jar synth upto-language-equivalence,plain,pure,safe,equal-conflict,minimize - 
success: No
failedStateSeparationProblems: []
failedEventStateSeparationProblems: {t1=[s1, s3], t2=[s2, s3], t3=[s1, s2, s3]}
```
However, it seems like the magic for automatically publishing an updated `apt.jar` last worked six years ago and there were commits from four years ago that already didn't cause such a build. Thus, you'll have to download the source and run `ant jar` yourself to actually get the fix. Sorry.

(`ant test` is also broken since our mockito version doesn't work with current JREs. I just had success with `JAVA_HOME=/path/to/openjdk11 ant test`. The next newer version this server has available is openjdk17 and there stuff already breaks.)

**Comment by NotANumberYang** [comment]
Many thanks for answering the question and fixing the bug!

Would it be possible to apply label splitting algorithms (or other techniques) to make LTSs solvable for `equal-conflict`? Do you have any suggestions regarding that?

**Comment by psychon** [comment]
Well... from your original example, I guess "maximal label splitting" (each edge in the LTS becomes its own transition) should have all the requested properties (except for `minimize`). Since each transition ends up with a single place in its preset, this should also mean that "non disjoint => equal".

So, in that sense I happen to know about a trivial algorithm for that. But usually that is not a satisfactory solution.

If I remember correctly, there is no algorithm for "intelligent label splitting" implemented in APT. And I also think I remember that the usual approaches are heuristics that just happen to work well, but have no formal guarantees, but I don't remember any details. Like, in your original TS, obviously t1 and t2 can just happen in parallel and there is no splitting needed for the `<t1><t2>|<t2><t1>` part of the language. However, from a quick look, I don't see how to make use of that without violating equal-conflictness for the "or `t3`" part of the language. (And since APT says that this LTS cannot be synthesised even when just asking for `upto-language-equivalence,equal-conflict`, I guess that still no nice solution exists. Even the language `(<t3><t4a>|<t1><t2><t4>|<t2><t1><t4>)*` is unsolvable and I don't think there is any useful label splitting left in there.)

So, sorry, I don't think I have much useful input for you and I already fail at solving your original example in my head.

("Not useful input" would include an exponential algorithm that just tries all possible label splittings and which surely is not satisfactory. One could do some relatively easy optimisations on that, but they wouldn't get rid of the exponential time requirement.)

**Comment by NotANumberYang** [comment]
We tried Petrify with option -efc (i.e., extended free-choice) for this example. It seems that Petrify splits t1 and t2 to make this example solvable.  
![paper_example_output dot](https://github.com/CvO-Theory/apt/assets/26345754/5588a93a-5414-4174-bee9-ae462093ed04)
